import { Seat, Participant, AssignmentRecord } from '@/types/festival';

export const ROWS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P'];
export const SEATS_PER_ROW = 34;

// Format seat number into 6 digit padded string for filename
export function formatSeatFilename(row: string, seatNumber: number): string {
  const padded = String(seatNumber).padStart(6, '0');
  return `${row}${padded}FDVC2026-CL.pdf`;
}

// Generate unique ticket code hash
export function generateTicketCode(row: string, seatNumber: number): string {
  const padded = String(seatNumber).padStart(3, '0');
  const randomHash = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `FDVC2026-${row}${padded}-${randomHash}`;
}

export function generateInitialSeats(): Seat[] {
  const seats: Seat[] = [];
  let globalSeatIndex = 1;

  ROWS.forEach((row) => {
    for (let col = 1; col <= SEATS_PER_ROW; col++) {
      let block: 'left' | 'center' | 'right' = 'center';
      if (col <= 8) {
        block = 'left';
      } else if (col >= 27) {
        block = 'right';
      } else {
        block = 'center';
      }

      const paddedNumber = String(globalSeatIndex).padStart(6, '0');
      const seatId = `${row}${col}`;

      seats.push({
        id: seatId,
        row: row,
        number: col,
        paddedNumber: paddedNumber,
        block: block,
        status: 'available',
        pdfFilename: formatSeatFilename(row, globalSeatIndex),
      });

      globalSeatIndex++;
    }
  });

  return seats;
}

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'part-1',
    name: 'Ana Francisca Pizarro Ruiz',
    type: 'solista',
    dancersCount: 1,
    school: 'Reflejos de Oriente Tarapacá',
    teacher: 'Adriana Campos',
    contactPerson: 'Adriana Campos',
    email: 'anapizarroruiz@gmail.com',
    phone: '+56982840695',
    instagram: '@anafcaaa',
    facebook: 'https://www.facebook.com/share/1CB7u9Q3jW/',
    tiktok: '@ana.franciska',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-2',
    name: 'Grupo Shazaditas Teens',
    type: 'grupo',
    dancersCount: 8,
    school: 'Estudio Shazadi Fitness Integrado',
    teacher: 'Shazadi',
    contactPerson: 'Shazadi',
    email: 'profesorashazadi@gmail.com',
    phone: '+56956208233',
    instagram: '@shazadioficial, @shazadi.fitnessintegrado',
    facebook: 'Shazadi',
    tiktok: 'Shazadi Fitness Integrado',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-3',
    name: 'Grupo Shazaditas Evolution',
    type: 'grupo',
    dancersCount: 10,
    school: 'Estudio Shazadi Fitness Integrado',
    teacher: 'Shazadi',
    contactPerson: 'Shazadi',
    email: 'profesorashazadi@gmail.com',
    phone: '+56956208233',
    instagram: '@shazadioficial, @shazadi.fitnessintegrado',
    facebook: 'Shazadi',
    tiktok: 'Shazadi Fitness Integrado',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-4',
    name: 'Grupo Shazaditas Essence',
    type: 'grupo',
    dancersCount: 8,
    school: 'Estudio Shazadi Fitness Integrado',
    teacher: 'Shazadi',
    contactPerson: 'Shazadi',
    email: 'profesorashazadi@gmail.com',
    phone: '+56956208233',
    instagram: '@shazadioficial, @shazadi.fitnessintegrado',
    facebook: 'Shazadi',
    tiktok: 'Shazadi Fitness Integrado',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-5',
    name: 'Ballet Shazaditas Styles',
    type: 'grupo',
    dancersCount: 12,
    school: 'Estudio Shazadi Fitness Integrado',
    teacher: 'Shazadi',
    contactPerson: 'Shazadi',
    email: 'profesorashazadi@gmail.com',
    phone: '+56956208233',
    instagram: '@shazadioficial, @shazadi.fitnessintegrado',
    facebook: 'Shazadi',
    tiktok: 'Shazadi Fitness Integrado',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-6',
    name: 'Adriana Campos',
    type: 'solista',
    dancersCount: 1,
    school: 'Reflejos de Oriente',
    teacher: 'Adriana Campos',
    contactPerson: 'Adriana Campos',
    email: 'adrianacamposchile@gmail.com',
    phone: '+56998312127',
    instagram: '@adrianacamposchile, @reflejosdeoriente',
    facebook: 'Adriana Campos Reflejos de Oriente',
    tiktok: '@adrianacamposchile, @reflejosdeorientechile',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-7',
    name: 'Adarah Bellydance',
    type: 'grupo',
    dancersCount: 6,
    school: 'Raks Al Hayat',
    teacher: 'Cristina Fuentes',
    contactPerson: 'Cristina Fuentes',
    email: 'bellydance.adarah@gmail.com',
    phone: '+56985492036',
    instagram: '@adarah_bellydance, @krissfuentes',
    facebook: 'Cristina Fuentes',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-8',
    name: 'Daisy Bustos Sánchez / Kardelens',
    type: 'solista',
    dancersCount: 1,
    school: 'Bailarina solista',
    teacher: 'Daisy Bustos Sánchez',
    contactPerson: 'Daisy Bustos Sánchez',
    email: 'duqsa.daisy@gmail.com',
    phone: '+56991453275',
    instagram: '@__kardelens',
    facebook: 'Daisy M Bustos S',
    tiktok: '@__kardelens',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-9',
    name: 'Priscilla Bellydancer',
    type: 'solista',
    dancersCount: 1,
    school: 'Raks El Hob',
    teacher: 'Priscilla Bellydancer',
    contactPerson: 'Priscilla Bellydancer',
    email: 'priscillavelarde@hotmail.com',
    phone: '+56961680169',
    instagram: '@priscilla_bellydance',
    facebook: '',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-10',
    name: 'Grupo de alumnas (Fabiola Andrade)',
    type: 'grupo',
    dancersCount: 15,
    school: 'Escuela de Danza Oriental Fabiola Andrade',
    teacher: 'Fabiola Andrade Benavides',
    contactPerson: 'Fabiola Andrade Benavides',
    email: 'fabiola.danzaa@gmail.com',
    phone: '+56962134849',
    instagram: '@fabioladanzaholistica, @siembrasdearte',
    facebook: 'Fabiola Andrade Benavides',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-11',
    name: 'Raks Mahaila',
    type: 'grupo',
    dancersCount: 10,
    school: 'Mahaila May y alumnas',
    teacher: 'María Soledad Lazo / Mahaila',
    contactPerson: 'María Soledad Lazo / Mahaila',
    email: 'mayartistico@gmail.com',
    phone: '+56996995261',
    instagram: '@danzaypilates_mahailamay',
    facebook: 'Mahaila May Lazo',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-12',
    name: 'Casandra (Solista)',
    type: 'solista',
    dancersCount: 1,
    school: 'Casandra',
    teacher: 'Mabel Casandra Parra Albarrán',
    contactPerson: 'Mabel Casandra Parra Albarrán',
    email: 'mabel.parra.albarran@gmail.com',
    phone: '+56999957255',
    instagram: '@casandra_albarran',
    facebook: 'Casandra Albarrán',
    tiktok: 'Casandra Bellydancer',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-13',
    name: 'Grupo Casandra',
    type: 'grupo',
    dancersCount: 8,
    school: 'Casandra',
    teacher: 'Mabel Casandra Parra Albarrán',
    contactPerson: 'Mabel Casandra Parra Albarrán',
    email: 'mabel.parra.albarran@gmail.com',
    phone: '+56999957255',
    instagram: '@casandra_albarran',
    facebook: 'Casandra Albarrán',
    tiktok: 'Casandra Bellydancer',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-14',
    name: 'Grupo Arwam al shams',
    type: 'grupo',
    dancersCount: 6,
    school: 'Academia Farida Warda',
    teacher: 'Farida Warda',
    contactPerson: 'Farida Warda',
    email: 'faridawarda.bailarina@gmail.com',
    phone: '+56975875954',
    instagram: '@arwamalshams',
    facebook: 'Academia Farida Warda',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-15',
    name: 'Grupo Festival Raks El Hob',
    type: 'grupo',
    dancersCount: 12,
    school: 'Festival Raks El Hob',
    teacher: 'Priscilla',
    contactPerson: 'Priscilla',
    email: 'priscillavelarde@hotmail.com',
    phone: '+56961680169',
    instagram: '@festival_raks_el_hob',
    facebook: '',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-16',
    name: 'Arwah al Azhar',
    type: 'grupo',
    dancersCount: 8,
    school: 'Sayes Bellydance',
    teacher: 'Vania Sayes',
    contactPerson: 'Vania Sayes',
    email: 'sayesvania77@gmail.com',
    phone: '+56956253440',
    instagram: '@arwahalazhar.ballet',
    facebook: '',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-17',
    name: 'Sofía Martínez',
    type: 'solista',
    dancersCount: 1,
    school: 'Sofía Martínez',
    teacher: 'Sofía Martínez',
    contactPerson: 'Sofía Martínez',
    email: 'ansolu23@hotmail.com',
    phone: '+569945391326',
    instagram: '@ansolu23',
    facebook: 'Sofía Hernández Martínez',
    tiktok: '@ansolu23',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-18',
    name: 'Grupo Habibi Danza',
    type: 'grupo',
    dancersCount: 10,
    school: 'Habibi Danza Cajón del Maipo',
    teacher: 'Cristina Acevedo',
    contactPerson: 'Cristina Acevedo',
    email: 'habibidanzacajondelmaipo@gmail.com',
    phone: '+56984556278',
    instagram: '@habibidanzacajondelmaipo',
    facebook: '',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-19',
    name: 'Grupo Will Bellydancer',
    type: 'grupo',
    dancersCount: 12,
    school: 'Escuela Will Bellydancer',
    teacher: 'Wilma Galleguillos Fuentes',
    contactPerson: 'Wilma Galleguillos Fuentes',
    email: 'willcarolina2@gmail.com',
    phone: '+56991428303',
    instagram: '@willbellydancer, @escuela_willbellydancer',
    facebook: 'Wilma Galleguillos Will Bellydancer San Bernardo',
    tiktok: '@willbellydancer2.0',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-20',
    name: 'Grupo Malikas',
    type: 'grupo',
    dancersCount: 6,
    school: 'Dana Amar',
    teacher: 'Dana Amar / Javiera Avendaño',
    contactPerson: 'Dana Amar / Javiera Avendaño',
    email: 'javiera.avendano@gmail.com',
    phone: '+56982194471',
    instagram: '@jaivalaseca',
    facebook: '',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-21',
    name: 'Grupo Zahra Al Ruh',
    type: 'grupo',
    dancersCount: 8,
    school: 'Dana Amar',
    teacher: 'Danahe Zablah / Claudia Álvarez',
    contactPerson: 'Danahe Zablah / Claudia Álvarez',
    email: 'claudialvarezc8@gmail.com',
    phone: '+56956036534',
    instagram: '@_bazar_clau',
    facebook: 'Claudia Andrea Álvarez Concha',
    tiktok: '@claudiaalvarez6354',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-22',
    name: 'Grupo Alsabalal',
    type: 'grupo',
    dancersCount: 8,
    school: 'Academia Farida Warda',
    teacher: 'Farida Warda',
    contactPerson: 'Farida Warda',
    email: 'faridawarda.bailarina@gmail.com',
    phone: '+56975875954',
    instagram: '@alsabalal',
    facebook: 'Academia Farida Warda',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-23',
    name: 'Nazarena',
    type: 'solista',
    dancersCount: 1,
    school: 'Dana Amar',
    teacher: 'Dana Amar / Antonia Paz Lama',
    contactPerson: 'Dana Amar / Antonia Paz Lama',
    email: 'antopazlama@gmail.com',
    phone: '+56972535664',
    instagram: '@antooo_lama',
    facebook: '',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-24',
    name: 'Raquel Farías',
    type: 'solista',
    dancersCount: 1,
    school: 'Mawal',
    teacher: 'Raquel Farías',
    contactPerson: 'Raquel Farías',
    email: 'raquel_fariasgordon@yahoo.es',
    phone: '+56997309988',
    instagram: '@profe.danza.arabe',
    facebook: '',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-25',
    name: 'Diana Valle',
    type: 'solista',
    dancersCount: 1,
    school: 'Diana Valle González',
    teacher: 'Diana Valle González',
    contactPerson: 'Diana Valle González',
    email: 'katherine.valle@gmail.com',
    phone: '+56995126639',
    instagram: '@dianavalle_danzadelvientre',
    facebook: '@diana.vallegonzalez',
    tiktok: '',
    assignedSeatsCount: 0,
  },
  {
    id: 'part-26',
    name: 'Anne Marie Lolas',
    type: 'solista',
    dancersCount: 1,
    school: 'Anne Marie Lolas',
    teacher: 'Anne Marie Lolas',
    contactPerson: 'Anne Marie Lolas',
    email: 'anne.lolas.s@gmail.com',
    phone: '+56992517727',
    instagram: '@anne_lolas_danzarabe',
    facebook: '',
    tiktok: '',
    assignedSeatsCount: 0,
  },
];

export const INITIAL_ASSIGNMENTS: AssignmentRecord[] = [];
